// Mock data for demo mode (no backend required)
export const mockAirdrops = [
  {
    id: 1,
    name: "Berachain",
    slug: "berachain",
    description: "High-performance EVM-identical L1 with Proof of Liquidity consensus",
    logoColor: "#ff5c00",
    logoInitial: "B",
    websiteUrl: "https://berachain.com",
    twitterUrl: "https://twitter.com/berachain",
    telegramUrl: "https://t.me/berachain",
    discordUrl: "https://discord.gg/berachain",
    category: "L1",
    chain: "Berachain",
    status: "active",
    rewardEstimate: "$500-2000",
    totalValue: "$50000000",
    difficulty: "medium",
    isFeatured: true,
    isVerified: true,
    participantsCount: 450000,
    taskCount: 8,
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 2,
    name: "Scroll",
    slug: "scroll",
    description: "Ethereum-equivalent zkRollup for scaling Ethereum",
    logoColor: "#ffeeda",
    logoInitial: "S",
    websiteUrl: "https://scroll.io",
    twitterUrl: "https://twitter.com/Scroll_ZKP",
    telegramUrl: null,
    discordUrl: "https://discord.gg/scroll",
    category: "L2",
    chain: "Scroll",
    status: "active",
    rewardEstimate: "$300-1500",
    totalValue: "$35000000",
    difficulty: "easy",
    isFeatured: true,
    isVerified: true,
    participantsCount: 890000,
    taskCount: 5,
    startDate: "2024-02-01",
    endDate: "2024-07-31",
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: 3,
    name: "Linea",
    slug: "linea",
    description: "Type 2 zero-knowledge Ethereum Virtual Machine by ConsenSys",
    logoColor: "#121212",
    logoInitial: "L",
    websiteUrl: "https://linea.build",
    twitterUrl: "https://twitter.com/ConsenSys",
    telegramUrl: "https://t.me/lineabuild",
    discordUrl: "https://discord.gg/linea",
    category: "L2",
    chain: "Linea",
    status: "active",
    rewardEstimate: "$200-800",
    totalValue: "$25000000",
    difficulty: "easy",
    isFeatured: true,
    isVerified: true,
    participantsCount: 1200000,
    taskCount: 6,
    startDate: "2024-01-20",
    endDate: "2024-08-15",
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: 4,
    name: "ZkSync Era",
    slug: "zksync-era",
    description: "zkSync Era is a Layer 2 protocol that scales Ethereum with cutting-edge ZK tech",
    logoColor: "#8b8b8b",
    logoInitial: "Z",
    websiteUrl: "https://zksync.io",
    twitterUrl: "https://twitter.com/zksync",
    telegramUrl: null,
    discordUrl: "https://discord.gg/zksync",
    category: "L2",
    chain: "zkSync",
    status: "upcoming",
    rewardEstimate: "$1000-5000",
    totalValue: "$100000000",
    difficulty: "hard",
    isFeatured: true,
    isVerified: true,
    participantsCount: 2500000,
    taskCount: 12,
    startDate: null,
    endDate: null,
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: 5,
    name: "LayerZero",
    slug: "layerzero",
    description: "An omnichain interoperability protocol connecting blockchains",
    logoColor: "#8247e5",
    logoInitial: "L",
    websiteUrl: "https://layerzero.network",
    twitterUrl: "https://twitter.com/LayerZero_Labs",
    telegramUrl: null,
    discordUrl: "https://discord.gg/layerzero",
    category: "Infrastructure",
    chain: "Multi-chain",
    status: "active",
    rewardEstimate: "$400-2000",
    totalValue: "$40000000",
    difficulty: "medium",
    isFeatured: false,
    isVerified: true,
    participantsCount: 670000,
    taskCount: 7,
    startDate: "2024-02-15",
    endDate: "2024-09-01",
    createdAt: "2024-02-15T10:00:00Z",
  },
  {
    id: 6,
    name: "EigenLayer",
    slug: "eigenlayer",
    description: "Restaking protocol enabling ETH stakers to secure additional protocols",
    logoColor: "#ff6b35",
    logoInitial: "E",
    websiteUrl: "https://eigenlayer.xyz",
    twitterUrl: "https://twitter.com/eigenlayer",
    telegramUrl: null,
    discordUrl: "https://discord.gg/eigenlayer",
    category: "Restaking",
    chain: "Ethereum",
    status: "active",
    rewardEstimate: "$500-3000",
    totalValue: "$75000000",
    difficulty: "hard",
    isFeatured: false,
    isVerified: true,
    participantsCount: 320000,
    taskCount: 4,
    startDate: "2024-03-10",
    endDate: "2024-10-01",
    createdAt: "2024-03-10T10:00:00Z",
  },
  {
    id: 7,
    name: "Manta Network",
    slug: "manta-network",
    description: "Multi-modular ecosystem for zero-knowledge applications",
    logoColor: "#00d4aa",
    logoInitial: "M",
    websiteUrl: "https://manta.network",
    twitterUrl: "https://twitter.com/mantanetwork",
    telegramUrl: "https://t.me/mantanetwork",
    discordUrl: "https://discord.gg/mantanetwork",
    category: "L2",
    chain: "Manta",
    status: "active",
    rewardEstimate: "$200-600",
    totalValue: "$15000000",
    difficulty: "easy",
    isFeatured: false,
    isVerified: true,
    participantsCount: 450000,
    taskCount: 5,
    startDate: "2024-01-25",
    endDate: "2024-07-15",
    createdAt: "2024-01-25T10:00:00Z",
  },
  {
    id: 8,
    name: "Starknet",
    slug: "starknet",
    description: "Validity rollup providing unlimited scale without compromising Ethereum's security",
    logoColor: "#1a1a2e",
    logoInitial: "S",
    websiteUrl: "https://starknet.io",
    twitterUrl: "https://twitter.com/Starknet",
    telegramUrl: null,
    discordUrl: "https://discord.gg/starknet",
    category: "L2",
    chain: "Starknet",
    status: "upcoming",
    rewardEstimate: "$800-4000",
    totalValue: "$80000000",
    difficulty: "hard",
    isFeatured: false,
    isVerified: true,
    participantsCount: 1100000,
    taskCount: 10,
    startDate: null,
    endDate: null,
    createdAt: "2024-04-01T10:00:00Z",
  },
  {
    id: 9,
    name: "Celestia",
    slug: "celestia",
    description: "First modular blockchain network enabling anyone to deploy their own blockchain",
    logoColor: "#7b68ee",
    logoInitial: "C",
    websiteUrl: "https://celestia.org",
    twitterUrl: "https://twitter.com/CelestiaOrg",
    telegramUrl: null,
    discordUrl: "https://discord.gg/celestia",
    category: "Infrastructure",
    chain: "Celestia",
    status: "ended",
    rewardEstimate: "$300-1500",
    totalValue: "$20000000",
    difficulty: "medium",
    isFeatured: false,
    isVerified: true,
    participantsCount: 780000,
    taskCount: 6,
    startDate: "2023-10-01",
    endDate: "2024-02-28",
    createdAt: "2023-10-01T10:00:00Z",
  },
  {
    id: 10,
    name: "Hyperliquid",
    slug: "hyperliquid",
    description: "Decentralized perpetual exchange with fully on-chain orderbook",
    logoColor: "#22c55e",
    logoInitial: "H",
    websiteUrl: "https://hyperliquid.xyz",
    twitterUrl: "https://twitter.com/HyperliquidX",
    telegramUrl: null,
    discordUrl: "https://discord.gg/hyperliquid",
    category: "DeFi",
    chain: "Hyperliquid",
    status: "active",
    rewardEstimate: "$1000-5000",
    totalValue: "$60000000",
    difficulty: "medium",
    isFeatured: false,
    isVerified: true,
    participantsCount: 180000,
    taskCount: 3,
    startDate: "2024-03-20",
    endDate: "2024-09-15",
    createdAt: "2024-03-20T10:00:00Z",
  },
];

export const mockTasks = [
  { id: 1, airdropId: 1, title: "Follow on Twitter", type: "social", url: "https://twitter.com/berachain", isCompleted: false },
  { id: 2, airdropId: 1, title: "Join Discord", type: "social", url: "https://discord.gg/berachain", isCompleted: false },
  { id: 3, airdropId: 1, title: "Test faucet", type: "onchain", url: "https://faucet.berachain.com", isCompleted: false },
  { id: 4, airdropId: 2, title: "Bridge ETH to Scroll", type: "onchain", url: "https://scroll.io/bridge", isCompleted: false },
  { id: 5, airdropId: 2, title: "Follow on Twitter", type: "social", url: "https://twitter.com/Scroll_ZKP", isCompleted: false },
  { id: 6, airdropId: 3, title: "Bridge to Linea", type: "onchain", url: "https://bridge.linea.build", isCompleted: false },
  { id: 7, airdropId: 3, title: "Mint NFT", type: "onchain", url: "https://linea.build/nft", isCompleted: false },
  { id: 8, airdropId: 4, title: "Connect wallet", type: "onchain", url: "https://zksync.io", isCompleted: false },
];

export const mockActivity = [
  { id: 1, type: "airdrop_added", message: "Berachain airdrop added", actorName: null, createdAt: "2024-01-15T10:00:00Z" },
  { id: 2, type: "airdrop_added", message: "Scroll airdrop added", actorName: null, createdAt: "2024-02-01T10:00:00Z" },
  { id: 3, type: "airdrop_updated", message: "Linea airdrop updated", actorName: null, createdAt: "2024-02-05T14:30:00Z" },
  { id: 4, type: "airdrop_added", message: "ZkSync Era airdrop added", actorName: null, createdAt: "2024-03-01T09:00:00Z" },
  { id: 5, type: "airdrop_updated", message: "EigenLayer airdrop updated", actorName: null, createdAt: "2024-03-12T16:45:00Z" },
];
