export const mockAirdrops: any[] = [
  {
    id: 1,
    name: "Hyperliquid",
    slug: "hyperliquid",
    description: "Decentralized perpetual DEX on its own L1 with on-chain order book and ultra-low latency trading.",
    logoColor: "#00c2ff",
    logoInitial: "HL",
    category: "DeFi",
    chain: "HYP",
    status: "active",
    rewardEstimate: "$500–2,000",
    totalValue: "$1.2B",
    difficulty: "easy",
    isFeatured: true,
    isVerified: true,
    participantsCount: 420000,
    taskCount: 4,
    endDate: null,
    websiteUrl: "https://hyperliquid.xyz",
    twitterUrl: "https://twitter.com/HyperliquidX",
    telegramUrl: null,
    discordUrl: "https://discord.gg/hyperliquid",
    referralUrl: "https://app.hyperliquid.xyz/",
  },
  {
    id: 2,
    name: "Monad",
    slug: "monad",
    description: "EVM-compatible L1 with 10,000 TPS throughput and 1-second block times, parallel execution engine.",
    logoColor: "#8b5cf6",
    logoInitial: "MON",
    category: "Layer 1",
    chain: "MON",
    status: "upcoming",
    rewardEstimate: "$200–800",
    totalValue: "$500M",
    difficulty: "medium",
    isFeatured: false,
    isVerified: true,
    participantsCount: 310000,
    taskCount: 6,
    endDate: null,
    websiteUrl: "https://monad.xyz",
    twitterUrl: "https://twitter.com/monad_xyz",
    telegramUrl: null,
    discordUrl: "https://discord.gg/monad",
    referralUrl: "https://monad.xyz",
  },
  {
    id: 3,
    name: "Berachain",
    slug: "berachain",
    description: "EVM-identical L1 using Proof-of-Liquidity consensus. Earn BGT by providing liquidity in native vaults.",
    logoColor: "#e8a845",
    logoInitial: "BERA",
    category: "Layer 1",
    chain: "BERA",
    status: "active",
    rewardEstimate: "$300–1,500",
    totalValue: "$750M",
    difficulty: "medium",
    isFeatured: false,
    isVerified: true,
    participantsCount: 275000,
    taskCount: 8,
    endDate: null,
    websiteUrl: "https://berachain.com",
    twitterUrl: "https://twitter.com/berachain",
    telegramUrl: null,
    discordUrl: "https://discord.gg/berachainofficial",
    referralUrl: "https://berachain.com",
  },
  {
    id: 4,
    name: "ZKsync",
    slug: "zksync",
    description: "Ethereum ZK rollup scaling solution with native account abstraction and EVM compatibility.",
    logoColor: "#1755f4",
    logoInitial: "ZK",
    category: "Layer 2",
    chain: "ETH",
    status: "ended",
    rewardEstimate: "Distributed",
    totalValue: "$400M",
    difficulty: "easy",
    isFeatured: false,
    isVerified: true,
    participantsCount: 695000,
    taskCount: 3,
    endDate: "2024-06-17",
    websiteUrl: "https://zksync.io",
    twitterUrl: "https://twitter.com/zksync",
    telegramUrl: null,
    discordUrl: "https://discord.gg/zksync",
    referralUrl: "https://zksync.io",
  },
  {
    id: 5,
    name: "Starknet",
    slug: "starknet",
    description: "Permissionless decentralized ZK-Rollup on Ethereum with STARK proofs and Cairo programming language.",
    logoColor: "#ec407a",
    logoInitial: "STRK",
    category: "Layer 2",
    chain: "ETH",
    status: "ended",
    rewardEstimate: "Distributed",
    totalValue: "$600M",
    difficulty: "medium",
    isFeatured: false,
    isVerified: true,
    participantsCount: 580000,
    taskCount: 5,
    endDate: "2024-02-20",
    websiteUrl: "https://starknet.io",
    twitterUrl: "https://twitter.com/Starknet",
    telegramUrl: "https://t.me/starknet",
    discordUrl: "https://discord.gg/starknet",
    referralUrl: "https://starknet.io",
  },
  {
    id: 6,
    name: "Scroll",
    slug: "scroll",
    description: "Native zkEVM Layer 2 for Ethereum, bytecode-compatible with full EVM equivalence and low fees.",
    logoColor: "#f59e0b",
    logoInitial: "SCR",
    category: "Layer 2",
    chain: "ETH",
    status: "active",
    rewardEstimate: "$100–400",
    totalValue: "$200M",
    difficulty: "easy",
    isFeatured: false,
    isVerified: true,
    participantsCount: 198000,
    taskCount: 4,
    endDate: null,
    websiteUrl: "https://scroll.io",
    twitterUrl: "https://twitter.com/Scroll_ZKP",
    telegramUrl: null,
    discordUrl: "https://discord.gg/scroll",
    referralUrl: "https://scroll.io",
  },
  {
    id: 7,
    name: "Eigenlayer",
    slug: "eigenlayer",
    description: "Ethereum restaking protocol enabling validators to secure multiple networks with the same staked ETH.",
    logoColor: "#3b82f6",
    logoInitial: "EIGEN",
    category: "Infrastructure",
    chain: "ETH",
    status: "active",
    rewardEstimate: "$200–1,000",
    totalValue: "$1.5B",
    difficulty: "hard",
    isFeatured: false,
    isVerified: true,
    participantsCount: 350000,
    taskCount: 7,
    endDate: null,
    websiteUrl: "https://eigenlayer.xyz",
    twitterUrl: "https://twitter.com/eigenlayer",
    telegramUrl: null,
    discordUrl: "https://discord.gg/eigenlayer",
    referralUrl: "https://app.eigenlayer.xyz/",
  },
  {
    id: 8,
    name: "Linea",
    slug: "linea",
    description: "ConsenSys-built zkEVM L2 on Ethereum. Powers the Ethereum ecosystem with MetaMask-native integration.",
    logoColor: "#121212",
    logoInitial: "LXP",
    category: "Layer 2",
    chain: "ETH",
    status: "active",
    rewardEstimate: "$50–300",
    totalValue: "$175M",
    difficulty: "easy",
    isFeatured: false,
    isVerified: true,
    participantsCount: 230000,
    taskCount: 5,
    endDate: null,
    websiteUrl: "https://linea.build",
    twitterUrl: "https://twitter.com/LineaBuild",
    telegramUrl: null,
    discordUrl: "https://discord.gg/linea",
    referralUrl: "https://linea.build",
  },
  {
    id: 9,
    name: "Sui Ecosystem",
    slug: "sui-defi",
    description: "DeFi protocols building on Sui's high-throughput Move-based blockchain. Multiple active incentive programs.",
    logoColor: "#4ca2ff",
    logoInitial: "SUI",
    category: "DeFi",
    chain: "SUI",
    status: "active",
    rewardEstimate: "$100–500",
    totalValue: "$300M",
    difficulty: "medium",
    isFeatured: false,
    isVerified: false,
    participantsCount: 155000,
    taskCount: 6,
    endDate: null,
    websiteUrl: "https://sui.io",
    twitterUrl: "https://twitter.com/SuiNetwork",
    telegramUrl: null,
    discordUrl: "https://discord.gg/sui",
    referralUrl: "https://sui.io",
  },
  {
    id: 10,
    name: "Taiko",
    slug: "taiko",
    description: "Based ZK-EVM rollup with based sequencing and multi-proof system for Ethereum scalability.",
    logoColor: "#e84040",
    logoInitial: "TAIKO",
    category: "Layer 2",
    chain: "ETH",
    status: "potential",
    rewardEstimate: "TBD",
    totalValue: "TBD",
    difficulty: "medium",
    isFeatured: false,
    isVerified: true,
    participantsCount: 88000,
    taskCount: 4,
    endDate: null,
    websiteUrl: "https://taiko.xyz",
    twitterUrl: "https://twitter.com/taikoxyz",
    telegramUrl: null,
    discordUrl: "https://discord.gg/taikoxyz",
    referralUrl: "https://taiko.xyz",
  },
  {
    id: 11,
    name: "Sophon",
    slug: "sophon",
    description: "Consumer blockchain built on ZK Stack focused on entertainment, gaming, and lifestyle applications.",
    logoColor: "#7c3aed",
    logoInitial: "SOPH",
    category: "Gaming",
    chain: "ETH",
    status: "upcoming",
    rewardEstimate: "$50–200",
    totalValue: "$100M",
    difficulty: "easy",
    isFeatured: false,
    isVerified: false,
    participantsCount: 62000,
    taskCount: 3,
    endDate: null,
    websiteUrl: "https://sophon.xyz",
    twitterUrl: "https://twitter.com/sophon",
    telegramUrl: "https://t.me/sophon",
    discordUrl: "https://discord.gg/sophon",
    referralUrl: "https://sophon.xyz",
  },
  {
    id: 12,
    name: "Grass",
    slug: "grass",
    description: "Decentralized data network that lets you monetize your unused bandwidth for AI training datasets.",
    logoColor: "#16a34a",
    logoInitial: "GRASS",
    category: "Infrastructure",
    chain: "SOL",
    status: "active",
    rewardEstimate: "$20–150",
    totalValue: "$80M",
    difficulty: "easy",
    isFeatured: false,
    isVerified: true,
    participantsCount: 540000,
    taskCount: 2,
    endDate: null,
    websiteUrl: "https://getgrass.io",
    twitterUrl: "https://twitter.com/getgrass_io",
    telegramUrl: "https://t.me/getgrass_io",
    discordUrl: "https://discord.gg/getgrass",
    referralUrl: "https://app.getgrass.io/register?referralCode=YOUR_CODE",
  },
];

export const mockNews: any[] = [
  {
    id: 1,
    title: "Hyperliquid Surpasses $10B in Daily DEX Volume",
    summary: "The perpetual DEX built on its own L1 has become the top derivatives platform by volume, outpacing Binance perps in user growth.",
    category: "DeFi",
    source: "The Block",
    url: "https://theblock.co",
    imageColor: "#00c2ff",
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    readTime: "3 min",
    tags: ["hyperliquid", "perps", "dex"],
  },
  {
    id: 2,
    title: "Monad Testnet Goes Live with 10,000 TPS Benchmark",
    summary: "Monad's public testnet officially launched showcasing parallel EVM execution. Community airdrop expected in Q3 2025.",
    category: "Layer 1",
    source: "CoinDesk",
    url: "https://coindesk.com",
    imageColor: "#8b5cf6",
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    readTime: "4 min",
    tags: ["monad", "testnet", "airdrop"],
  },
  {
    id: 3,
    title: "EigenLayer TVL Hits New All-Time High of $20B",
    summary: "Ethereum restaking protocol EigenLayer continues its explosive growth as new AVS services launch on mainnet.",
    category: "Infrastructure",
    source: "DeFi Llama",
    url: "https://defillama.com",
    imageColor: "#3b82f6",
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    readTime: "2 min",
    tags: ["eigenlayer", "restaking", "tvl"],
  },
  {
    id: 4,
    title: "Berachain Proof-of-Liquidity Explained: How to Maximize BGT Rewards",
    summary: "A deep-dive into Berachain's novel PoL consensus mechanism and strategies to earn maximum validator emissions.",
    category: "Guide",
    source: "Bankless",
    url: "https://bankless.com",
    imageColor: "#e8a845",
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    readTime: "8 min",
    tags: ["berachain", "pol", "guide"],
  },
  {
    id: 5,
    title: "Grass Network Reaches 1M Active Nodes Milestone",
    summary: "The decentralized bandwidth-sharing network hits 1 million active nodes, with Season 2 rewards campaign still live.",
    category: "Infrastructure",
    source: "CryptoSlate",
    url: "https://cryptoslate.com",
    imageColor: "#16a34a",
    publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    readTime: "3 min",
    tags: ["grass", "despin", "nodes"],
  },
  {
    id: 6,
    title: "ZK Rollup Wars: Scroll vs Linea vs Taiko in 2025",
    summary: "Comparative analysis of the top ZK-EVM L2 solutions and which one is best positioned for a large airdrop.",
    category: "Analysis",
    source: "Messari",
    url: "https://messari.io",
    imageColor: "#f59e0b",
    publishedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    readTime: "6 min",
    tags: ["scroll", "linea", "taiko", "zk"],
  },
  {
    id: 7,
    title: "Top 10 Airdrop Opportunities in June 2025",
    summary: "Monthly roundup of the highest-potential crypto airdrops with step-by-step task guides for each project.",
    category: "Guide",
    source: "Ouwibo Cloud",
    url: "#",
    imageColor: "#f97316",
    publishedAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    readTime: "10 min",
    tags: ["airdrop", "monthly", "guide"],
  },
  {
    id: 8,
    title: "Sui Ecosystem DeFi TVL Crosses $500M as New Protocols Launch",
    summary: "Multiple new DeFi protocols are going live on Sui with incentive campaigns and early-user reward programs.",
    category: "DeFi",
    source: "DeFi Pulse",
    url: "#",
    imageColor: "#4ca2ff",
    publishedAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    readTime: "4 min",
    tags: ["sui", "defi", "tvl"],
  },
];

export const mockTasks: any[] = [
  { id: 1, name: "Bridge ETH to Hyperliquid", airdropId: 1, taskType: "bridge", completed: true },
  { id: 2, name: "Make 10 trades on HL", airdropId: 1, taskType: "trade", completed: true },
  { id: 3, name: "Follow Monad on Twitter", airdropId: 2, taskType: "social", completed: false },
  { id: 4, name: "Join Monad Discord", airdropId: 2, taskType: "social", completed: false },
  { id: 5, name: "Stake on Berachain testnet", airdropId: 3, taskType: "stake", completed: false },
];

export const mockActivity: any[] = [
  { id: 1, type: "airdrop_added", message: "Hyperliquid added to tracker — 4 tasks", createdAt: new Date(Date.now() - 3600000).toISOString() },
  { id: 2, type: "task_completed", message: "Completed: Bridge ETH to Hyperliquid", createdAt: new Date(Date.now() - 7200000).toISOString() },
  { id: 3, type: "airdrop_added", message: "Monad testnet is now live — start farming", createdAt: new Date(Date.now() - 86400000).toISOString() },
  { id: 4, type: "status_change", message: "Scroll airdrop status updated to Active", createdAt: new Date(Date.now() - 172800000).toISOString() },
  { id: 5, type: "airdrop_added", message: "Grass Season 2 rewards campaign active", createdAt: new Date(Date.now() - 259200000).toISOString() },
];
